var relations = [
    {
        "user":{
            "id":50,
            "email":"shadowrf+5@gmail.com",
            "lat":"46.4639",
            "lon":"30.7386"
        },
        "first_degree":[
            {
                "id":53,
                "email":"shadowrf+6@gmail.com",
                "lat":"50.4333",
                "lon":"30.5167",
                "second_degree":[
                    {
                        "id":54,
                        "email":"shadowrf+8@gmail.com",
                        "lat":"47.506851",
                        "lon":"19.045776"
                    },
                    {
                        "id":55,
                        "email":"shadowrf+10@gmail.com",
                        "lat":"48.210033",
                        "lon":"16.363449"
                    }
                ]
            },
            {
                "id":54,
                "email":"shadowrf+7@gmail.com",
                "lat":"49.8407",
                "lon":"24.0305",
                "second_degree":[
                    {
                        "id":54,
                        "email":"shadowrf+9@gmail.com",
                        "lat":"48.891132",
                        "lon":"18.042297"
                    }
                ]
            }
        ]
    }
];